### ISSUE TITLE
[BUG] - Error in setting up the project

### ISSUE THREAD

**Issue by bEluga0000** [tcet-opensource/hacktober-fest#36]
### Describe the bug

When we try to set up the project locally facing a issue .when we going to set up i am getting the local host link but after that its showing a error that "The following dependencies are imported but could not be resolved:"  react-router-dom whinch is in navbar.jsx file.

### Actual behavior

Getting the react-router-dom error after pnpm run dev

### Expected behavior

We should not get that error

### How to Reproduce?

1. pnpm run dev
![Uploading issues.png…]()

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by bEluga0000** [comment]
it can be resolved using the 
"pnpm add  react-router-dom" 
before setting up the project

**Comment by Ratikant-rout** [comment]
Can You Pls Provide The Access To Solve This Issue I Will Be More Glad To Fufill The Requirements

**Comment by Pavan-kalyan99** [comment]
> it can be resolved using the "pnpm add react-router-dom" before setting up the project

hi, I didn't face any error while setup the project .
please check the packages.json file & check react -router -dom is install or not.
