### ISSUE TITLE
Shorten Hero Section Content, Adjust Register Button Position

### ISSUE THREAD

**Issue by Neeharikajha** [tcet-opensource/hacktober-fest#43]
### Describe the improvement

1. The hero section content currently contains 7 lines of text, which is too long. It should be shortened to 3-4 lines for better aesthetics and user experience.

2. The main register button's position should be adjusted to maintain the desired layout and design.

![image](https://github.com/tcet-opensource/hacktober-fest/assets/136990222/f99b0ffb-0e4d-44cb-95a5-5e4eda689621)

### Why do we need this?

Improvement in the design consistency, aesthetic considerations.

### Do you have a proposed solution?

Possible solutions :

1. shortening hero section content
2. Adjusting location of main register button so that it does not shift.

### Do you want to work on this feature?

- [ ] I am willing to implement this feature.

### Terms and Conditions

- [ ] I agree to follow this project's Code of Conduct

**Comment by Harsh3363** [comment]
I would like to implement the changes please assign this to me

**Comment by Harsh3363** [comment]
@Neeharikajha can you explain a little about the desired design of the register button

**Comment by kamalika0363** [comment]
> @Neeharikajha can you explain a little about the desired design of the register button

Consider this design 
![image](https://github.com/tcet-opensource/hacktober-fest/assets/59131714/0de027d3-d113-488e-b565-05b099227fba)
as you can see the content is a bit access in the current frontend, you need to reduce that along with maintaining the design aspects

**Comment by Harsh3363** [comment]
> > @Neeharikajha can you explain a little about the desired design of the register button
> 
> Consider this design ![image](https://user-images.githubusercontent.com/59131714/272351225-0de027d3-d113-488e-b565-05b099227fba.png) as you can see the content is a bit access in the current frontend, you need to reduce that along with maintaining the design aspects

Sure I will try to implement this.
