### ISSUE TITLE
[FEATURE] - FAQ section should be above the footer.

### ISSUE THREAD

**Issue by 0amirk** [tcet-opensource/hacktober-fest#46]
#### The current site:
![Screenshot (70)](https://github.com/tcet-opensource/hacktober-fest/assets/133527168/de76ad8e-8dc3-4289-b0f0-f5c90ae2be5f)
![Screenshot (71)](https://github.com/tcet-opensource/hacktober-fest/assets/133527168/b12b99dd-6da9-482b-b5db-39a1d6fbb422)

#### We need:
![Screenshot (69)](https://github.com/tcet-opensource/hacktober-fest/assets/133527168/0a8984cb-da9d-4bf5-a952-19b021b70443)

### Why do we need this?

Improvement in the design consistency, aesthetic considerations.

### Do you have a proposed solution?

Solution:
Editing the src/pages/home.jsx file

### Do you want to work on this feature?

- [ ] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitBansal321** [comment]
could you assgin this issue to me
