### ISSUE TITLE
[FEATURE] - <Remove the border from logo>

### ISSUE THREAD

**Issue by MohitBansal321** [tcet-opensource/hacktober-fest#50]
### Describe the improvement

It does not align with style pattern you follow in the navbar
before
![TCET before](https://github.com/tcet-opensource/hacktober-fest/assets/78220157/a916fa1c-b606-4111-b6b9-1eb0f625ea5b)
after
![TCET after](https://github.com/tcet-opensource/hacktober-fest/assets/78220157/ffdc286b-ad89-45c4-9ad9-41d49a9cff5a)

### Why do we need this?

Improvement in the design consistency and aesthetic considerations.

### Do you have a proposed solution?

Remove the border class from the logo element in src/Components/Navbar

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by bEluga0000** [comment]
@MohitBansal321 is anyone working on this issue. if not assign to me.

**Comment by MohitBansal321** [comment]
Yes I am working on it
